import {
  Timestamp,
  QueryDocumentSnapshot,
  CollectionReference,
  DocumentSnapshot,
  DocumentData,
  documentId,
  collection,
  doc,
  query,
  where,
  SnapshotOptions,
  FirestoreDataConverter,
  getDocs,
  getDocsFromServer,
  getDoc,
  limit,
} from 'firebase/firestore'
import {
  ActionCodeSettings,
  EmailAuthProvider,
  User as BackendAuthUser,
  updatePassword,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  sendEmailVerification,
  sendPasswordResetEmail,
  applyActionCode,
  verifyPasswordResetCode,
  confirmPasswordReset,
  fetchSignInMethodsForEmail,
  reauthenticateWithCredential,
} from 'firebase/auth'

export {
  Timestamp,
  QueryDocumentSnapshot,
  CollectionReference,
  DocumentSnapshot,
  DocumentData,
  FirestoreDataConverter,
  SnapshotOptions,
  documentId,
  collection,
  doc,
  query,
  where,
  getDocs,
  getDocsFromServer,
  getDoc,
  limit,
  BackendAuthUser,
  ActionCodeSettings,
  EmailAuthProvider,
  updatePassword,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  sendEmailVerification,
  sendPasswordResetEmail,
  applyActionCode,
  verifyPasswordResetCode,
  confirmPasswordReset,
  fetchSignInMethodsForEmail,
  reauthenticateWithCredential,
}
